/* Generated By:JavaCC: Do not edit this line. GramaticaConstants.java */
package analizadorCC;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GramaticaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PUNTO_COMA = 8;
  /** RegularExpression Id. */
  int LLAVE_A = 9;
  /** RegularExpression Id. */
  int LLAVE_C = 10;
  /** RegularExpression Id. */
  int PAR_A = 11;
  /** RegularExpression Id. */
  int PAR_C = 12;
  /** RegularExpression Id. */
  int INCR = 13;
  /** RegularExpression Id. */
  int DECR = 14;
  /** RegularExpression Id. */
  int MAS = 15;
  /** RegularExpression Id. */
  int MULT = 16;
  /** RegularExpression Id. */
  int IGUAL_IGUAL = 17;
  /** RegularExpression Id. */
  int IGUAL = 18;
  /** RegularExpression Id. */
  int OR = 19;
  /** RegularExpression Id. */
  int AND = 20;
  /** RegularExpression Id. */
  int VAR = 21;
  /** RegularExpression Id. */
  int IMPRIMIR = 22;
  /** RegularExpression Id. */
  int SI = 23;
  /** RegularExpression Id. */
  int SINO = 24;
  /** RegularExpression Id. */
  int FALSO = 25;
  /** RegularExpression Id. */
  int VERDADERO = 26;
  /** RegularExpression Id. */
  int NULO = 27;
  /** RegularExpression Id. */
  int NUM = 28;
  /** RegularExpression Id. */
  int ID = 29;
  /** RegularExpression Id. */
  int NUM_D = 30;
  /** RegularExpression Id. */
  int CADENA = 31;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"\\t\"",
    "<token of kind 6>",
    "<token of kind 7>",
    "\";\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"*\"",
    "\"==\"",
    "\"=\"",
    "\"||\"",
    "\"&&\"",
    "\"var\"",
    "\"imprimir\"",
    "\"si\"",
    "\"sino\"",
    "\"false\"",
    "\"true\"",
    "\"nulo\"",
    "<NUM>",
    "<ID>",
    "<NUM_D>",
    "<CADENA>",
  };

}
