/* Gramatica.java */
/* Generated By:JavaCC: Do not edit this line. Gramatica.java */
package analizadorCC;

import estructuras.*;
import estructuras.sents.*;
import estructuras.exp.*;
import compartido.*;
/**
 *
 * @author Ricardo
 */


public class Gramatica implements GramaticaConstants {

  final public Nodo Start() throws ParseException {Documento raiz;
    Sentencias sents = new Sentencias();
    Nodo sent;
    sent = Sent();
sents.add(sent);
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case VAR:
      case IMPRIMIR:{
        ;
        break;
        }
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      sent = Sent();
sents.add(sent);
    }
raiz = new Documento(sents);
        {if ("" != null) return raiz;}
    throw new Error("Missing return statement in function");
  }

  final public Nodo Sent() throws ParseException {Nodo s;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case IMPRIMIR:{
      s = getImprimir();
      break;
      }
    case VAR:{
      s = getDeclaracion();
      break;
      }
    default:
      jj_la1[1] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
{if ("" != null) return s;}
    throw new Error("Missing return statement in function");
  }

  final public Imprimir getImprimir() throws ParseException {Expresion e;
    jj_consume_token(IMPRIMIR);
    jj_consume_token(PAR_A);
    e = E();
    jj_consume_token(PAR_C);
    jj_consume_token(PUNTO_COMA);
{if ("" != null) return new Imprimir(e);}
    throw new Error("Missing return statement in function");
  }

  final public Declaracion getDeclaracion() throws ParseException {Id id;
    Expresion exp = new ValorExpresion();
    jj_consume_token(VAR);
    id = getId();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case IGUAL:{
      jj_consume_token(IGUAL);
      exp = E();
      break;
      }
    default:
      jj_la1[2] = jj_gen;
      ;
    }
    jj_consume_token(PUNTO_COMA);
{if ("" != null) return new Declaracion(id, exp);}
    throw new Error("Missing return statement in function");
  }

  final public Expresion E() throws ParseException {Expresion e;
    e = getExpresion();
{if ("" != null) return e;}
    throw new Error("Missing return statement in function");
  }

  final public Expresion getExpresion() throws ParseException {Expresion e1;
    Token idVar, t1;
    Nodo id;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case NUM_D:{
      t1 = jj_consume_token(NUM_D);
e1 = new ValorExpresion(new Valor(Double.parseDouble(t1.image.toString())));
      break;
      }
    case NUM:{
      t1 = jj_consume_token(NUM);
e1 = new ValorExpresion(new Valor(Double.parseDouble(t1.image.toString())));
      break;
      }
    case CADENA:{
      e1 = Cadena();
      break;
      }
    case PAR_A:{
      jj_consume_token(PAR_A);
      e1 = E();
      jj_consume_token(PAR_C);
      break;
      }
    default:
      jj_la1[3] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
{if ("" != null) return e1;}
    throw new Error("Missing return statement in function");
  }

  final public ValorExpresion Cadena() throws ParseException {Token t1;
    t1 = jj_consume_token(CADENA);
String son = t1.image.toString().replaceAll("\u005c"", "");
        {if ("" != null) return new ValorExpresion(new Valor(son));};
    throw new Error("Missing return statement in function");
  }

  final public Id getId() throws ParseException {Token t1;
    t1 = jj_consume_token(ID);
{if ("" != null) return new Id(t1.image.toString());};
    throw new Error("Missing return statement in function");
  }

  /** Generated Token Manager. */
  public GramaticaTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[4];
  static private int[] jj_la1_0;
  static {
      jj_la1_init_0();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x600000,0x600000,0x40000,0xd0000800,};
   }

  /** Constructor with InputStream. */
  public Gramatica(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Gramatica(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new GramaticaTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 4; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 4; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public Gramatica(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new GramaticaTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 4; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 4; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public Gramatica(GramaticaTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 4; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(GramaticaTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 4; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk_f() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[32];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 4; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 32; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

}
