
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizador;

/** CUP generated class containing symbol constants. */
public class CupSimbolos {
  /* terminals */
  public static final int cadena = 13;
  public static final int decimal = 18;
  public static final int numero = 14;
  public static final int s_if = 5;
  public static final int imprimir = 4;
  public static final int nulo = 3;
  public static final int s_else = 6;
  public static final int llaveC = 11;
  public static final int igual = 7;
  public static final int EOF = 0;
  public static final int verdadero = 16;
  public static final int llaveA = 10;
  public static final int id = 15;
  public static final int error = 1;
  public static final int par_c = 9;
  public static final int var = 2;
  public static final int par_a = 8;
  public static final int falso = 17;
  public static final int punto_coma = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "var",
  "nulo",
  "imprimir",
  "s_if",
  "s_else",
  "igual",
  "par_a",
  "par_c",
  "llaveA",
  "llaveC",
  "punto_coma",
  "cadena",
  "numero",
  "id",
  "verdadero",
  "falso",
  "decimal"
  };
}

